import os

journals = {
    "INTERNATIONAL CONFERENCE ON SOLID STATE DEVICES AND MATERIALS SCIENCE": "SSDM",
    "IEEECVF CONFERENCE ON COMPUTER VISION AND PATTERN RECOGNITION, CVPR": "CVPR",
    "PROCEEDINGS OF THE THIRTIETH IJCAI 2021": "IJCAI 2021",
    "COMPUTER VISION": "CV",
    "2020 IEEECVF CONFERENCE ON COMPUTER VISION AND PATTERN RECOGNITION (CVPR)": "CVPR 2020",
    "IEEE TRANSACTIONS ON INTELLIGENT TRANSPORTATION SYSTEMS": "IEEE T INTELL TRANSP",
    "IEEE ACCESS": "IEEE ACCESS",
    "2021 IEEECVF INTERNATIONAL CONFERENCE ON COMPUTER VISION (ICCV 2021)": "ICCV 2021",
    "MEDICAL IMAGE COMPUTING AND COMPUTER ASSISTED INTERVENTION": "MICCAI",
    "INFORMATION FUSION": "INFORM FUSION",
    "INTELLIGENT AUTOMATION AND SOFT COMPUTING": "IASC",
    "NEURAL PROCESSING LETTERS": "Neural Process Lett",
    "ACM TRANSACTIONS ON GRAPHICS": "ACM Trans. Graph",
    "IEEE TRANSACTIONS ON COGNITIVE AND DEVELOPMENTAL SYSTEMS": "IEEE T COGN DEV SYST",
    "IEEE TRANSACTIONS ON CIRCUITS AND SYSTEMS FOR VIDEO TECHNOLOGY": "IEEE Trans Circuits Syst Video Technol",
    "IEEE Conference on Computer Vision and Pattern Recognition": "CVPR",
    "IEEE TRANSACTIONS ON IMAGE PROCESSING": "TIP",
    "NEUROCOMPUTING": "NEUROCOMPUTING",
    "VISUAL COMPUTER": "VISUAL COMPUTER",
    "COMPUTER AIDED GEOMETRIC DESIGN": "COMPUTER AIDED GEOMETRIC DESIGN",
    "IET INTELLIGENT TRANSPORT SYSTEMS": "IET INTELL TRANSP SY",
    "IEEE TRANSACTIONS ON MULTIMEDIA": "ITM",
    "INTERNATIONAL JOURNAL OF DISTRIBUTED SENSOR NETWORKS": "IJDSN",
    "2019 IEEECVF INTERNATIONAL CONFERENCE ON COMPUTER VISION (ICCV 2019)": "ICCV 2019",
    "ACM TRANSACTIONS ON MULTIMEDIA COMPUTING COMMUNICATIONS AND APPLICATION": "ACM T MULTIM COMPUT",
    "INFORMATION SCIENCES": "INFORM SCIENCES",
    "IEEE transactions on visualization and computer graphics": "IEEE Trans. Visual. Comput. Graphics",
    "SENSORS": "SENSORS",
    "IEEE TRANSACTIONS ON NEURAL NETWORKS AND LEARNING SYSTEMS": "ITNNLS",
    "PATTERN RECOGNITION": "PR",
    "IEEE TRANSACTIONS ON VISUALIZATION AND COMPUTER GRAPHICS": "IEEE Trans. Visual. Comput. Graphics",
    "2023 IEEECVF CONFERENCE ON COMPUTER VISION AND PATTERN RECOGNITION (CVPR)": "CVPR 2023",
}

def rename():
    for input in os.listdir('论文同行评价'):
        file_names = input.split('-')
        file_names[1] = file_names[1].strip().removesuffix('刊物')
        if journals.get(file_names[1]) is None:
            print(f'Cannot find journal {file_names[1]}')
            continue

        file_names[1] = journals[file_names[1]] + '刊物'
        new_file_name = '-'.join(file_names)
        os.rename(f'论文同行评价/{input}', f'论文同行评价/{new_file_name}')


if __name__ == '__main__':
    rename()